### ISSUE TITLE
Make public/release indigo [and hydro] version

### ISSUE THREAD

**Issue by corot** [turtlebot/turtlebot_arm#13]
This is mostly to initiate a conversation between people somehow involved with this repo (mainly with @mikeferguson) about how we will handle this stack. I have no intention to maintain a hydro branch (nor release, of course), but we can do it if you think that it will be too horrible to have a gap in the ROS versions. That said, those are the steps to do next, I suppose:
- [x] Recuperate lost packages (#4)
- [x] Release indigo
- [x] Update ROS wiki
- [x] Announce the update

What do you think?

BTW @mikeferguson, could you set indigo-devel as the default branch, or give me permits to do so?
Thanks

**Comment by mikeferguson** [comment]
Looks like you have a branch setup already. I no longer have any time to work on this project, so I won't be of much help. Good luck.

**Comment by corot** [comment]
yes... I was afraid it will be my duty.... :see_no_evil:

well, indigo branch is working fine, but... I omitted important packages and I didn't pay any attention to install configuration. So the indigo release is something to happen in the medium term.

Btw, I have a couple of questions:

Concerning the kinect calibration, is it fundamentally outdated, replaced by newer packages? Or it's still the good aproach and just needs to be updated to indigo?

And can you  set indigo-devel as the default branch, or give me permits to do so?

Thanks!

**Comment by mikeferguson** [comment]
There is no replacement for the kinect calibration. The main reason I didn't catkinize it along with the other stuff is that I didn't have hardware to test on, so it was going to be done last, and I never got to it. It looks as though it already uses the newer C++ style OpenCV API, so I think the only update it might need are:
- Updates to use pcl_conversions since PCL removed ROS features.
- Eigen build fixes?

I could try to take a look at this over the weekend and get it compiling -- but somebody else will have to actually test it on hardware.

Indigo branch is now default.

**Comment by corot** [comment]
OK, thanks. Making it compiling was straightforward, but I never tried with
the hardware. I'll get to it sometime in the following weeks.

2014-08-08 20:37 GMT+02:00 Michael Ferguson notifications@github.com:

**Comment by corot** [comment]
Finally, no hydro. We just make a jump in the versions sequence, sorry to the world.
